#############################################
# basic software                            #
# generated_makefile_config.mk              #
#                                           #
# This file is intended to create lists of  #
# c files basic software to be compiled     #
#                                           #
# Created on: Jun 25, 2025                  #
# Author: Autogenerated Python xx           #
#############################################


###########################################
# Create basic software source files list #
###########################################
BSW_SRC_C_FILES := \
${BSW}drivers/cpu/nvic/nvic.c \
${BSW}drivers/cpu/systick/systick.c \
${BSW}drivers/mcu/clock/clock.c \
${BSW}drivers/mcu/dma/dma.c \
${BSW}drivers/mcu/gpio/gpio.c \
${BSW}drivers/mcu/spi/spi.c \
${BSW}drivers/mcu/usart/usart.c


#############################################
# Create basic software include folder list #
#############################################
BSW_INCLUDE_FOLDER := \
-I ${BSW}configuration \
-I ${BSW}drivers \
-I ${BSW}drivers/cpu/nvic \
-I ${BSW}drivers/cpu/systick \
-I ${BSW}drivers/mcu/clock \
-I ${BSW}drivers/mcu/dma \
-I ${BSW}drivers/mcu/gpio \
-I ${BSW}drivers/mcu/spi \
-I ${BSW}drivers/mcu/timer \
-I ${BSW}drivers/mcu/usart \
-I ${BSW}library/error \
-I ${BSW}library/fault \
