#############################################
# applications                              #
# generated_makefile_config.mk              #
#                                           #
# This file is intended to create lists of  #
# c files application software to be        #
# compiled                                  #
#                                           #
# Created on: Jun 25, 2025                  #
# Author: Autogenerated Python xx           #
#############################################


#################################################
# Create application software source files list #
#################################################
APPLICATIONS_SRC_C_FILES_TARGET1 := \
${APPLICATIONS}tests/test_usart.c \
${APPLICATIONS}tests/test_spi_target1.c \
${APPLICATIONS}main.c

APPLICATIONS_SRC_C_FILES_TARGET2 := \
${APPLICATIONS}tests/test_usart.c \
${APPLICATIONS}tests/test_spi_target2.c \
${APPLICATIONS}main.c


###################################################
# Create application software include folder list #
###################################################
APPLICATIONS_INCLUDE_FOLDER := \
-I ${APPLICATIONS}tests
