name: C CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update arm_none_eabi_gcc
      run: |
        sudo apt-get -y install gcc-arm-none-eabi
    - name: make
      run: |
        cd 02-software
  
        echo "Build first target"
        make clean
        make target1.elf
        echo "Build folder structure"
        tree build
  
        echo "Build second target"
        make clean
        make target2.elf
        echo "Build folder structure"
        tree build

        echo "Build first target debug"
        make clean
        make target1.elf debug
        echo "Build folder structure"
        tree build
